### ISSUE TITLE
Hi - not sure if you check support@xybernic

### ISSUE THREAD

**Issue by Balance-Sun** [MKGitHub/DevelopmentGuidelinesAndBestPractices#1]
So i will just message you here 

is there any possibility that menu eclipse still works in Mojave? 

It is a useful concept - especially with the amount of apps going into the status bar at the moment

Is there any way you could put the source code up if you are not using it anymore

Maybe  let's develop something new together

**Comment by MKGitHub** [comment]
I sorry Menu Eclipse has been abandoned since dark menu became available in macOS. By tmaybe in the future, the code is too old and written in Obj-C so it would not be useful :-(

**Comment by Balance-Sun** [comment]
ok next time... but maybe a similar idea... to keep the menu bar clean.. send me a message if you would like to work on something else together. I will build most of it. But maybe i will need your help along the way.,
